#!/bin/sh

host=$(uname -n)
iface=${2:-}
hash=$(printf '%s%s' "$host" "$iface" | sha256sum | cut -c1-10)

case "$1" in
mac)
  printf "02:%s\n" "$(printf '%s' "$hash" | sed 's/../&:/g; s/:$//')"
  ;;
sha)
  printf "%s\n" "$hash"
  ;;
"")
  printf "Missing argument, use mac or sha\n"
  exit 1
  ;;
*)
  printf "Invalid argument '%s', use mac or sha\n" "$1"
  exit 1
  ;;
esac
